language: php

services:
  - mysql
  
php:
  - 7.0

before_script:
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - mysql -e 'create database fiercephish;'
  - php artisan key:generate
  - php artisan migrate

script:
    - vendor/bin/phpunit